/* ============================================================================
   Copy to clipboard, for the two pages that exist to get content into the panel.

   WHY THIS IS SHARED RATHER THAN WRITTEN TWICE. The email console and the message
   deck are generated by different modules and have nothing else in common, but they
   have the same job: something on screen, and the exact text behind it going to the
   clipboard in one press. Copied into both, the clipboard fallback below would be
   the kind of code that gets fixed in one place and left broken in the other.

   TWO CONSTRAINTS SHAPE ALL OF IT, and neither is obvious from the code.

   1. THESE PAGES ARE OPENED FROM DISK. They are written under factory/, which
      pages.yml does not publish, so file:// is the normal case rather than the edge
      case. That rules out fetch for loading anything, and it means
      navigator.clipboard may be unavailable: a file:// page is not a secure context
      in every browser. execCommand('copy') is deprecated and is the thing that
      works there, so it is the fallback rather than the first attempt.

   2. THE TEXT CANNOT LIVE IN A SCRIPT BLOCK. An AMP email contains </script>,
      which would terminate the block and truncate the source at exactly the point
      nobody would notice, since the visible part would look complete. A textarea
      holds it as raw text instead, and reading .value returns the original bytes
      with entities decoded. Only two characters need escaping on the way in.
   ========================================================================== */

/* & first, so entities are not invented, then < so </textarea> cannot appear. */
export function escapeForBox(text) {
    return String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;');
}

/* One hidden source. id is what the button and any iframe point at. */
export function sourceBox(id, name, text) {
    if (text === null || text === undefined) return '';
    return `
    <textarea hidden id="${id}" data-name="${name}">${escapeForBox(text)}</textarea>`;
}

/* The behaviour for both pages. Buttons opt in with class="copy" and
   data-src="<id>"; iframes opt in with data-src="<id>" and are given the source as
   srcdoc, which is how a preview renders without a server. */
export function copyScript() {
    return `
<script>
  for (const frame of document.querySelectorAll('iframe[data-src]')) {
      const store = document.getElementById(frame.dataset.src);
      if (store) frame.srcdoc = store.value;
  }

  async function put(text) {
      try {
          if (navigator.clipboard && window.isSecureContext) {
              await navigator.clipboard.writeText(text);
              return true;
          }
      } catch (error) { /* fall through to the older path */ }
      const pad = document.createElement('textarea');
      pad.value = text;
      pad.setAttribute('readonly', '');
      pad.style.position = 'fixed';
      pad.style.top = '-1000px';
      document.body.appendChild(pad);
      pad.select();
      let done = false;
      try { done = document.execCommand('copy'); } catch (error) { done = false; }
      pad.remove();
      return done;
  }

  for (const btn of document.querySelectorAll('button.copy')) {
      btn.addEventListener('click', async () => {
          const store = document.getElementById(btn.dataset.src);
          if (!store) return;
          const label = btn.dataset.label || btn.textContent;
          btn.dataset.label = label;
          const ok = await put(store.value);
          /* The character count is the useful half of the confirmation: it says
             something arrived, and roughly how much, without opening the file. */
          btn.textContent = ok
              ? 'Copied, ' + store.value.length.toLocaleString() + ' characters'
              : 'Press Ctrl or Cmd C';
          btn.classList.add('done');
          setTimeout(() => { btn.textContent = label; btn.classList.remove('done'); }, 2600);
      });
  }
</script>`;
}
